---
# TODO: добавить настройку пользователей по ролям
- debug:
    msg: "{{ postgresql_users }}"
    
- name: PostgreSQL | Настройка пользователей PostgreSQL
  community.postgresql.postgresql_user:
    db: "postgres"
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
  with_items: "{{ postgresql_users }}"
  become: true
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
