---
# Variable configuration.
- name: Debian | Импорт переменных
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: RedHat | Импорт переменных
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
  - ansible_os_family == 'RedHat'
  - ansible_distribution != 'Fedora'

- name: Fedora | Импорт переменных
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Fedora'

# - name: Определение postgresql_repo
#   set_fact:
#     postgresql_repo: "{{ __postgresql_repo }}"
#   when: postgresql_repo is not defined

# - name: Определение postgresql_disablerepo
#   set_fact:
#     postgresql_disablerepo: "{{ __postgresql_disablerepo | default(omit, true) }}"
#   when: postgresql_disablerepo is not defined

# - name: Определение postgresql_enablerepo
#   set_fact:
#     postgresql_enablerepo: "{{ __postgresql_enablerepo | default(omit, true) }}"
#   when: postgresql_enablerepo is not defined

